# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f103741970c74f9a58e30b1231727cc714af06ae02c00f8b509cc7178cc7406b517aaa2928663a1edb8c778f64422a0d5514a68868de34fac4f4c9ce3984f1b

test:
  secret_key_base: d17f3aa37e954f6b2391a2a37463c70c8374e8ab19fe61e7482857f806c4f0d21d998d76912a45f8c6be7fcb13f6aa6c0dda4c6ac647aa4e4378902fd36e6ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
